name: polkawallet_plugin_karura
description: Karura network plugin for Polkawallet.
version: 0.3.7
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  charts_flutter: ^0.11.0
  http: ^0.13.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1
  json_annotation: ^4.0.1
  get_storage: ^2.0.2
  device_info: ^2.0.1
  graphql_flutter: ^5.0.0-nullsafety.5
  liquid_progress_indicator: ^0.3.2
  polkawallet_sdk: ^0.3.7
  polkawallet_ui: ^0.3.6
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

dependency_overrides:
 polkawallet_sdk:
   path: ../sdk
 polkawallet_ui:
   path: ../ui

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/js_service_karura/dist/main.js
    - assets/images/
    - assets/images/tokens/
    - assets/images/2.0X/
    - assets/images/3.0X/
